[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python src/main.py"
healthcheckPath = "/api/summary"
healthcheckTimeout = 60
restartPolicyType = "always"

[[volumes]]
mountPath = "/data"
